# Generated by Django 2.2.4 on 2020-07-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instamall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='store',
            name='mall',
        ),
        migrations.AddField(
            model_name='store',
            name='malls',
            field=models.ManyToManyField(related_name='stores', to='instamall.Mall'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
